language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install pytest
 - pip install pytest-cov
 - pip install coveralls

script:
 - pytest --cov=app/api/tests
 
branches:
  only:
  - master
  - stable

after_success:
 - coveralls
